name: Dotfile deployment
run-name: ${{ github.actor }} is deploying dotfiles
on: [workflow_dispatch, push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: shellcheck
          execute_install_scripts: true
          version: 1.0

      - name: Deploy dotfiles
        run: ./first-run.sh

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: nvim-packer.log
